<?php
// module/Album/view/article/article/add.phtml:

$title = 'Add new article';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('article', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();

/*
<?= $this->form()->openTag($form); ?>

<input type="hidden" name="id" value="<?= $form->get('id')->getValue() ?>">
<input type="text" name="id" value="<?= $form->get('title')->getValue() ?>">

<button name="submit" type="submit">Add article</button>

<?= $this->form()->closeTag() ?>
*/ 
