<?php
$title = 'Edit article';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<?php if (count($errors)): ?>
    <div class="alert alert-danger">
        <?php var_dump($errors); ?>
    </div>
<?php endif; ?>

<form method="post" action="/article/<?= $form->get('id')->getValue() ?>/edit">
    <div class="form-group">
        <label for="title"><?= $form->get('title')->getLabel() ?></label>
        <input type="text" name="title" id="title" value="<?= $form->get('title')->getValue() ?>">
    </div>

    <input type="hidden" name="id" value="<?= $form->get('id')->getValue() ?>">

    <button type="submit" class="btn btn-default">Update</button>
</form>
