<?php
$title = 'Login';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>

<?php if (count($errors)): ?>
    <div class="alert alert-danger">
        <?php var_dump($errors); ?>
    </div>
<?php endif; ?>

<div class="container">
    <form method="post" action="/login">
        <div class="form-group">
            <label for="email"><?= $form->get('email')->getLabel() ?></label>
            <input class="form-control" type="email" name="email" id="email" value="<?= $form->get('email')->getValue() ?>">
        </div>

        <div class="form-group">
            <label for="password"><?= $form->get('password')->getLabel() ?></label>
            <input class="form-control" type="password" name="password" id="password" value="<?= $form->get('password')->getValue() ?>">
        </div>

        <?= $this->formHidden($form->get('id')) ?>

        <button type="submit" class="btn btn-default">Login</button>
    </form>
</div>
